FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

ARG MONGO_URI
ARG NODE_ENV
ARG MONGO_INITDB_ROOT_USERNAME
ARG MONGO_INITDB_ROOT_PASSWORD
ARG ME_CONFIG_MONGODB_ADMINUSERNAME
ARG ME_CONFIG_MONGODB_ADMINPASSWORD
ARG JWT_SECRET
ARG JWT_EXPIRES
ARG JWT_COOKIE_EXPIRE

ENV MONGO_URI=${MONGO_URI}
ENV NODE_ENV=${NODE_ENV}
ENV MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
ENV MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
ENV ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
ENV ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_EXPIRES=${JWT_EXPIRES}
ENV JWT_COOKIE_EXPIRE=${JWT_COOKIE_EXPIRE}

EXPOSE 5050

CMD ["npm", "start"]

